# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  v2laygroundresourceapi:
    image: v2laygroundresourceapi
    build:
      context: .
      dockerfile: V2Layground.ResourceApi/Dockerfile
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
